#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kiwix"
name = "Kiwix"
description.en = "Sharing Web content with people without Internet access"
description.fr = "Partager du contenu Web avec des personnes sans accès à Internet"

version = "3.8.1~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.kiwix.org/"
demo = "http://library.kiwix.org/"
admindoc = "https://wiki.kiwix.org/wiki/Kiwix-serve/"
code = "https://github.com/kiwix/kiwix-tools"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-3.8.1.tar.gz"
    amd64.sha256 = "46557f9a3c3eaada2556a957cf5bc662c07dc6286e8924e04fa3a173f83ff6dd"
    arm64.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-aarch64-3.8.1.tar.gz"
    arm64.sha256 = "7b00940e1f5e4642e4ef6e7262543893e105b20e9e97be5352e129c591fa29da"
    armhf.url = "https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armv6-3.8.1.tar.gz"
    armhf.sha256 = "0f7e052d99c0d13e690c1855ac04e0d06a3b9201e5459f26a9bfeba016b482c8"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
